# Generated by Django 5.0.3 on 2026-02-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='e.g. Minimalist, Creative, Engineering, etc.', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('layout_config', models.JSONField(help_text='Defines sections and their ordering for this template')),
                ('css_override', models.TextField(blank=True, help_text='Template specific styles')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(default='My Resume', max_length=255)),
                ('personal_info', models.JSONField(default=dict)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('awards', models.JSONField(default=list)),
                ('is_ai_optimized', models.BooleanField(default=False)),
                ('last_ai_optimization', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='auip_institution.studentacademicregistry')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resumetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCustomizationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_jd', models.TextField(help_text='The job description the student is tailoring for')),
                ('ai_suggestions_applied', models.JSONField(default=list)),
                ('ats_score_before', models.IntegerField(default=0)),
                ('ats_score_after', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.studentresume')),
            ],
        ),
    ]
