# Generated by Django 5.1.15 on 2026-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='abstract',
            field=models.TextField(blank=True, help_text='Detailed project abstract'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='approved_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='batch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='project_link',
            field=models.URLField(blank=True, help_text='External link (GitHub, Live Demo, etc.)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='research_paper',
            field=models.FileField(blank=True, null=True, upload_to='projects/research/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='description',
            field=models.TextField(blank=True, help_text='Short description or overview'),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='file',
            field=models.FileField(help_text='Main Project Submission/Source Code', upload_to='projects/submissions/%Y/%m/'),
        ),
    ]
