# Generated by Django 5.1.15 on 2026-03-09 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_attendancerecord_options_and_more'),
        ('projects', '0002_studentproject_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='co_authors',
            field=models.CharField(blank=True, help_text='Comma separated co-author names', max_length=500),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_projects', to='academic.department'),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='research_area',
            field=models.CharField(blank=True, help_text='e.g. Artificial Intelligence, Mechanical Engineering', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='file',
            field=models.FileField(blank=True, help_text='Main Project Submission/Source Code', null=True, upload_to='projects/submissions/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faculty_id', models.IntegerField()),
                ('faculty_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REQUESTED_CHANGES', 'Changes Requested'), ('VERIFIED', 'Verified / Approved'), ('EXCELLENT', 'Outstanding / Featured')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='projects.studentproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
