services:
  # PostgreSQL Database
  #  postgres:
  #    image: postgres:15-alpine
  #    container_name: auip-postgres
  #    environment:
  #      POSTGRES_DB: auip_db
  #      POSTGRES_USER: auip_user
  #      POSTGRES_PASSWORD: auip_password_dev
  #    volumes:
  #      - postgres_data:/var/lib/postgresql/data
  #    ports:
  #      - "5432:5432"
  #    networks:
  #      - auip-network
  #    healthcheck:
  #      test: [ "CMD-SHELL", "pg_isready -U auip_user -d auip_db" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: auip-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - auip-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auip-backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - backend_static:/app/static
      - backend_media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=aws-1-ap-southeast-1.pooler.supabase.com
      - TURNSTILE_ENABLED=True
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - auip-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: auip-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - auip-network

volumes:
  postgres_data:
  backend_static:
  backend_media:


networks:
  auip-network:
    driver: bridge
