# Generated by Django 5.1.15 on 2026-02-21 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='institution_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(default='ACCEPTED', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_role', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialpost')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.socialpost')),
            ],
            options={
                'unique_together': {('post', 'user_id', 'user_role')},
            },
        ),
    ]
