# Generated by Django 5.1.15 on 2026-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_socialpost_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_url',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='chats/'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/%Y/%m/'),
        ),
    ]
