# Generated by Django 5.0.3 on 2026-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_chatmessage_attachment_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='received',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='deleted_for',
            field=models.JSONField(default=list, help_text='List of participant IDs who deleted this chat'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='invite_link_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='participants_metadata',
            field=models.JSONField(default=dict, help_text='Invite statuses, roles, etc.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='chats/media/'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='participants',
            field=models.JSONField(help_text='List of {id, role, name} participants'),
        ),
    ]
