# Generated by Django 5.1.15 on 2026-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_read_chatmessage_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='drive_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='post_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('PLACEMENT', 'Placement')], default='GENERAL', max_length=20),
        ),
    ]
