# Generated by Django 5.1.15 on 2026-03-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialpost_drive_id_socialpost_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_role', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status_tracking',
            field=models.JSONField(default=dict, help_text='Map of {user_id_role: {delivered_at, seen_at}}'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='social_chat_session_ff89ce_idx'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='social.chatsession'),
        ),
    ]
