# Generated by Django 5.1.15 on 2026-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_joinrequest_remove_chatmessage_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='invite_expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='open_invite',
            field=models.BooleanField(default=False, help_text='If True, anyone with link can join bypassing eligibility'),
        ),
    ]
