# Generated by Django 5.0.3 on 2026-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_group', models.CharField(choices=[('ALL', 'All Members'), ('STUDENTS', 'All Students'), ('FACULTY', 'All Faculty'), ('ELIGIBLE', 'Eligible Students (Drive-Specific)'), ('APPLIED', 'Applied Students (Drive-Specific)')], default='ALL', max_length=20)),
                ('drive_id', models.IntegerField(blank=True, help_text='ID of the related placement drive', null=True)),
                ('importance', models.IntegerField(default=1, help_text='1: Normal, 2: High, 3: Urgent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System Alert'), ('PLACEMENT', 'Placement Update'), ('ACADEMIC', 'Academic Alert'), ('COMMUNICATION', 'Centralized Message'), ('BLOG', 'New Blog Post'), ('NEWSLETTER', 'Newsletter')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_url', models.CharField(blank=True, help_text='Action URL for the notification', max_length=512)),
            ],
        ),
    ]
