# Generated by Django 5.2.5 on 2025-08-17 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_alter_answer_attempt_alter_answer_question_and_more'),
        ('quizzes', '0004_studentquizassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='awarded_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.option'),
        ),
    ]
