# Generated by Django 5.0.3 on 2026-02-28 07:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('degree_type', models.CharField(default='B.Tech', max_length=50)),
                ('duration_years', models.PositiveSmallIntegerField(choices=[(2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years')], default=4)),
                ('total_semesters', models.PositiveSmallIntegerField(default=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'ordering': ['department__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['course__code', 'name'], 'verbose_name': 'Batch (Legacy)', 'verbose_name_plural': 'Batches (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Course (Legacy)', 'verbose_name_plural': 'Courses (Legacy)'},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.AddField(
            model_name='batch',
            name='roll_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of student roll numbers enrolled in this batch', size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_courses', to='academic.academicprogram'),
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=10)),
                ('max_strength', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.academicprogram')),
            ],
            options={
                'verbose_name': 'Class Section',
                'verbose_name_plural': 'Class Sections',
                'ordering': ['program__code', 'semester_number', 'name'],
                'unique_together': {('program', 'academic_year', 'semester_number', 'name')},
            },
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_courses', to='academic.department'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicprogram')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['program__code', 'semester_number'],
                'unique_together': {('program', 'academic_year', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab / Practical'), ('PROJECT', 'Project'), ('ELECTIVE', 'Elective'), ('AUDIT', 'Audit Course')], default='THEORY', max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('is_placement_relevant', models.BooleanField(default=False, help_text='Flag subjects that are relevant to placement preparation')),
                ('placement_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="e.g. ['DSA', 'DBMS', 'OS'] — used by exam engine for auto-question tagging", size=None)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.academicprogram')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab'), ('TUTORIAL', 'Tutorial')], default='LECTURE', max_length=20)),
                ('topic_covered', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academic.classsection')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-session_date', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Links to FacultyAcademicRegistry.employee_id', max_length=50)),
                ('faculty_name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.academicyear')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.classsection')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academic.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'ordering': ['-academic_year__start_date', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(db_index=True, max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused'), ('OD', 'On Duty')], default='ABSENT', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academic.attendancesession')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['session__session_date', 'roll_number'],
                'unique_together': {('session', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(db_index=True, help_text='Links to StudentAcademicRegistry.roll_number', max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed'), ('DETAINED', 'Detained (< 75% attendance)')], default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academic.classsection')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['semester__semester_number', 'subject__code', 'roll_number'],
                'unique_together': {('roll_number', 'subject', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(db_index=True, max_length=50)),
                ('assessment_type', models.CharField(choices=[('CIA1', 'CIA 1'), ('CIA2', 'CIA 2'), ('MID', 'Mid-Term'), ('ASSIGNMENT', 'Assignment'), ('LAB', 'Lab Record'), ('VIVA', 'Viva'), ('PROJECT', 'Project'), ('FINAL', 'Final Exam (External)')], max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_marks', models.PositiveIntegerField(default=25)),
                ('remarks', models.TextField(blank=True)),
                ('entered_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='academic.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Internal Mark',
                'verbose_name_plural': 'Internal Marks',
                'ordering': ['-semester__semester_number', 'subject__code', 'roll_number'],
                'unique_together': {('roll_number', 'subject', 'semester', 'assessment_type')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='List of topics covered in this unit', size=None)),
                ('hours_required', models.PositiveSmallIntegerField(default=6)),
                ('ai_question_weight', models.FloatField(default=1.0, help_text='Weight for AI question generation (higher = more questions from this unit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Syllabus Unit',
                'verbose_name_plural': 'Syllabus Units',
                'ordering': ['subject__code', 'unit_number'],
                'unique_together': {('subject', 'unit_number')},
            },
        ),
    ]
