# Generated by Django 5.1.15 on 2026-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_full_academic_infrastructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-session_date', 'subject__code']},
        ),
        migrations.AlterModelOptions(
            name='internalmark',
            options={},
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='roll_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
    ]
