# Generated by Django 5.0.3 on 2026-02-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('conditions', models.JSONField(help_text="e.g. {'readiness_score_min': 40, 'activity_days_min': 5}")),
                ('actions', models.JSONField(help_text="e.g. {'allow_placement': true, 'require_mock': true}")),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content_structure',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='StudentIntelligenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_score', models.IntegerField(default=0, help_text='Derived from active usage')),
                ('readiness_score', models.IntegerField(default=0, help_text='Placement readiness (0-100)')),
                ('interest_matrix', models.JSONField(default=dict, help_text='Weighted interests based on behavior logs')),
                ('skill_matrix', models.JSONField(default=dict, help_text='Verified skills + implied skills from activities')),
                ('active_controls', models.JSONField(default=dict, help_text='Enabled/Disabled features based on policies')),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intel_profile', to='auip_institution.studentacademicregistry')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('CLICK', 'Button/Link Click'), ('SEARCH', 'Search Query'), ('QUIZ_START', 'Started Quiz'), ('BLOG_READ', 'Read Blog Post'), ('RESUME_BUILD', 'Editing Resume'), ('COMMUNICATION', 'Chat/Message Sent')], max_length=20)),
                ('target_id', models.CharField(blank=True, help_text='ID of the object interacted with', max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='auip_institution.studentacademicregistry')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'event_type'], name='governance__student_73140c_idx'), models.Index(fields=['timestamp'], name='governance__timesta_67b487_idx')],
            },
        ),
    ]
