# Generated by Django 5.1.15 on 2026-02-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_governancepolicy_alter_newsletter_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceBrainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50, unique=True)),
                ('weights_metadata', models.JSONField(help_text='Serialized weights or hyperparameters for the behavioral engine')),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('samples_trained', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_by_id', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='media_url',
            field=models.URLField(blank=True, help_text='Image or Video URL', null=True),
        ),
        migrations.AddField(
            model_name='studentintelligenceprofile',
            name='manual_overrides',
            field=models.JSONField(default=dict, help_text='Policy overrides by faculty'),
        ),
        migrations.AddField(
            model_name='studentintelligenceprofile',
            name='risk_factor',
            field=models.FloatField(default=0.0, help_text='0.0 to 1.0 probability of policy violation'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_id',
            field=models.IntegerField(help_text='ID of the Faculty/Admin/Student posting'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('ADMIN', 'Admin'), ('STUDENT', 'Student')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentintelligenceprofile',
            name='behavior_score',
            field=models.IntegerField(default=70, help_text='Derived from active usage'),
        ),
        migrations.AlterField(
            model_name='studentintelligenceprofile',
            name='readiness_score',
            field=models.IntegerField(default=50, help_text='Placement readiness (0-100)'),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_role', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='governance.blog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='governance.blogcomment')),
            ],
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='governance.blog')),
            ],
            options={
                'unique_together': {('blog', 'user_id', 'user_role')},
            },
        ),
    ]
