# Generated by Django 5.1.15 on 2026-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_governancebrainstate_mediaattachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='mediaattachment',
            name='file_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='blogs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.CharField(default='INSTITUTIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletters/'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='uploaded_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
