# Generated by Django 5.0.3 on 2026-02-20 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTrendInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('insight_content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_period', models.CharField(help_text='e.g., Spring 2024', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AIQuerySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('context_type', models.CharField(choices=[('CAREER', 'Career Advice'), ('RESUME', 'Resume Analysis'), ('TECH', 'Technical Doubt')], default='CAREER', max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='auip_institution.studentacademicregistry')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResumeInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='ATS/Compatibility score (0-100)')),
                ('suggested_roles', models.JSONField(default=list, help_text='AI suggested job roles')),
                ('missing_skills', models.JSONField(default=list)),
                ('improvement_plan', models.TextField()),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='auip_institution.studentacademicregistry')),
            ],
        ),
    ]
