# Generated by Django 5.1.15 on 2026-02-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of the authenticated user (Student/Admin/Faculty)', null=True)),
                ('user_role', models.CharField(blank=True, help_text='Role of the user at the time of session', max_length=50, null=True)),
                ('student_id', models.IntegerField(blank=True, help_text='Legacy Student Registry ID for deep student integration', null=True)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('context_type', models.CharField(default='GENERAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuerySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('query_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('context_type', models.CharField(choices=[('CAREER', 'Career Advice'), ('RESUME', 'Resume Analysis'), ('TECH', 'Technical Doubt')], default='CAREER', max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('drive_id', models.IntegerField(blank=True, null=True)),
                ('fit_score', models.IntegerField(default=0, help_text='0-100 score matching student to JD')),
                ('missing_keywords', models.JSONField(default=list)),
                ('suggested_improvements', models.TextField()),
                ('technical_weaknesses', models.JSONField(default=list)),
                ('communication_weaknesses', models.JSONField(default=list)),
                ('raw_jd_copy', models.TextField(blank=True, help_text='Copy of JD at time of analysis')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DROPOUT_RISK', 'Dropout Risk'), ('PLACEMENT_READINESS', 'Placement Readiness')], max_length=50)),
                ('target_identifier', models.CharField(help_text='Roll number or Batch year', max_length=255)),
                ('summary', models.TextField()),
                ('ai_logic_explanation', models.TextField(help_text='LLM generated reasoning for the report values')),
                ('data_snapshot', models.JSONField(help_text='Raw data metrics at time of report')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(default='RESUME', max_length=50)),
                ('content_chunk', models.TextField()),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector representation for semantic search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementTrendInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('insight_content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResumeInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('score', models.IntegerField(help_text='ATS/Compatibility score (0-100)')),
                ('suggested_roles', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('improvement_plan', models.TextField()),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intelligence.aichatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('using_rag', models.BooleanField(default=False)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_used', models.ManyToManyField(blank=True, to='intelligence.llmcontext')),
            ],
        ),
    ]
