# Generated by Django 5.0.3 on 2026-02-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
        ('intelligence', '0001_initial'),
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DROPOUT_RISK', 'Dropout Risk'), ('PLACEMENT_READINESS', 'Placement Readiness')], max_length=50)),
                ('target_identifier', models.CharField(help_text='Roll number or Batch year', max_length=255)),
                ('summary', models.TextField()),
                ('ai_logic_explanation', models.TextField(help_text='LLM generated reasoning for the report values')),
                ('data_snapshot', models.JSONField(help_text='Raw data metrics at time of report')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='placementtrendinsight',
            name='data_period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresumeinsight',
            name='suggested_roles',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ATSAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.IntegerField(default=0, help_text='0-100 score matching student to JD')),
                ('missing_keywords', models.JSONField(default=list)),
                ('suggested_improvements', models.TextField()),
                ('technical_weaknesses', models.JSONField(default=list)),
                ('communication_weaknesses', models.JSONField(default=list)),
                ('raw_jd_copy', models.TextField(blank=True, help_text='Copy of JD at time of analysis')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placement.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auip_institution.studentacademicregistry')),
            ],
        ),
        migrations.CreateModel(
            name='LLMContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='RESUME', max_length=50)),
                ('content_chunk', models.TextField()),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector representation for semantic search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_contexts', to='auip_institution.studentacademicregistry')),
            ],
        ),
        migrations.CreateModel(
            name='LLMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('using_rag', models.BooleanField(default=False)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context_used', models.ManyToManyField(blank=True, to='intelligence.llmcontext')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auip_institution.studentacademicregistry')),
            ],
        ),
    ]
