# Generated by Django 5.0.3 on 2026-02-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
        ('intelligence', '0003_remove_placementtrendinsight_data_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatconversation',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='ID of the authenticated user (Student/Admin/Faculty)', null=True),
        ),
        migrations.AddField(
            model_name='aichatconversation',
            name='user_role',
            field=models.CharField(blank=True, help_text='Role of the user at the time of session', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aichatconversation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='auip_institution.studentacademicregistry'),
        ),
    ]
