# Generated by Django 5.1.15 on 2026-02-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='email',
            field=models.EmailField(db_index=True, default='temp@auip.edu', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='last_login_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$mock_hash', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Institutional Admin')], default='STUDENT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorizedaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
