# Generated by Django 5.0.3 on 2026-02-18 08:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0002_remove_authorizedaccount_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPreSeededRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyPreSeededRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreSeededRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authorizedaccount',
            name='registry_ref',
        ),
        migrations.RemoveField(
            model_name='authorizedaccount',
            name='student_profile',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='auth_account',
        ),
        migrations.RenameModel(
            old_name='AcademicRegistry',
            new_name='StudentAcademicRegistry',
        ),
        migrations.AlterModelOptions(
            name='studentacademicregistry',
            options={'verbose_name_plural': 'Student Academic Registries'},
        ),
        migrations.CreateModel(
            name='AdminAuthorizedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_ua', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registry_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auip_institution.adminpreseededregistry')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAuthorizedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('courses_handling', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_ua', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registry_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auip_institution.facultypreseededregistry')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAuthorizedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_ua', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_ref', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auip_institution.studentacademicregistry')),
                ('registry_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auip_institution.studentpreseededregistry')),
            ],
        ),
        migrations.DeleteModel(
            name='PreSeededRegistry',
        ),
        migrations.DeleteModel(
            name='AuthorizedAccount',
        ),
        migrations.DeleteModel(
            name='FacultyProfile',
        ),
    ]
