# Generated by Django 5.0.3 on 2026-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0003_adminpreseededregistry_facultypreseededregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicregistry',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='passout_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='sgpa_history',
            field=models.JSONField(default=dict, help_text='Semester-wise GPA mapping'),
        ),
    ]
