# Generated by Django 5.0.3 on 2026-02-19 16:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0004_studentacademicregistry_admission_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAcademicRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('courses_handling', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facultyauthorizedaccount',
            name='courses_handling',
        ),
        migrations.RemoveField(
            model_name='facultyauthorizedaccount',
            name='department',
        ),
        migrations.RemoveField(
            model_name='facultyauthorizedaccount',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='facultyauthorizedaccount',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='facultypreseededregistry',
            name='invitation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultypreseededregistry',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultypreseededregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentpreseededregistry',
            name='invitation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpreseededregistry',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpreseededregistry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facultyauthorizedaccount',
            name='academic_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auip_institution.facultyacademicregistry'),
        ),
    ]
