# Generated by Django 5.0.3 on 2026-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0005_facultyacademicregistry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultypreseededregistry',
            name='activation_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facultypreseededregistry',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpreseededregistry',
            name='activation_token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentpreseededregistry',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
