# Generated by Django 5.0.3 on 2026-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0006_facultypreseededregistry_activation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauthorizedaccount',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='adminauthorizedaccount',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='facultyauthorizedaccount',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='facultyauthorizedaccount',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studentauthorizedaccount',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studentauthorizedaccount',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
