# Generated by Django 5.0.3 on 2026-02-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0007_add_name_fields_to_authorized_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpreseededregistry',
            name='activation_token',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminpreseededregistry',
            name='invitation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminpreseededregistry',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminpreseededregistry',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultypreseededregistry',
            name='activation_token',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentpreseededregistry',
            name='activation_token',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True),
        ),
    ]
