# Generated by Django 5.0.3 on 2026-02-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0008_increase_token_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyacademicregistry',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyacademicregistry',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
