# Generated by Django 5.1.15 on 2026-03-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_full_academic_infrastructure'),
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyacademicregistry',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_faculty', to='academic.department'),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='academic.department'),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='program_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='academic.academicprogram'),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='section_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='academic.classsection'),
        ),
        migrations.AddField(
            model_name='studentacademicregistry',
            name='semester_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='academic.semester'),
        ),
    ]
