# Generated by Django 5.1.15 on 2026-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_institution', '0010_facultyacademicregistry_department_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyacademicregistry',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='facultyacademicregistry',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
