# Generated by Django 5.0.3 on 2026-02-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auip_institution', '0009_alter_facultyacademicregistry_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('package_details', models.CharField(help_text='e.g., 12 LPA', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active (Accepting Applications)'), ('CLOSED', 'Closed'), ('RESULTS', 'Results Announced')], default='DRAFT', max_length=20)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('min_10th_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('min_12th_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('eligible_branches', models.JSONField(default=list, help_text="List of eligible branch names (e.g. ['CSE', 'IT'])")),
                ('eligible_batches', models.JSONField(default=list, help_text='List of eligible batch years (e.g. [2024, 2025])')),
                ('other_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('PLACED', 'Placed')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='auip_institution.studentacademicregistry')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.placementdrive')),
            ],
            options={
                'unique_together': {('drive', 'student')},
            },
        ),
    ]
