# Generated by Django 5.0.3 on 2026-02-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('SCREENING', 'Resume Screening'), ('TEST', 'Online Technical Test'), ('GD', 'Group Discussion'), ('TECH_INT', 'Technical Interview'), ('HR_INT', 'HR Interview'), ('OFFER', 'Offer Extended')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='AI or Interviewer feedback')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='placement.placementapplication')),
            ],
            options={
                'ordering': ['application', 'id'],
            },
        ),
    ]
