# Generated by Django 5.1.15 on 2026-02-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placementprocessstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='allowed_active_backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='cgpa_to_percentage_multiplier',
            field=models.DecimalField(decimal_places=2, default=9.5, help_text='Used dynamically to convert CGPA to %', max_digits=4),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='is_broadcasted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='jd_document',
            field=models.FileField(blank=True, null=True, upload_to='placements/jds/'),
        ),
    ]
