# Generated by Django 5.1.15 on 2026-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_placementdrive_allowed_active_backlogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='chat_session_id',
            field=models.UUIDField(blank=True, help_text='Linked ChatSession ID', null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='contact_details',
            field=models.JSONField(default=list, help_text='Emails/Phone numbers found in JD'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='custom_criteria',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic/Manual fields like 'Inter Percent', 'Backlog Policy'"),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='experience_years',
            field=models.CharField(blank=True, help_text='e.g. 0-2 Years, Freshers Only', max_length=100),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='hiring_process',
            field=models.JSONField(default=list, help_text="Steps: e.g. ['Online Test', 'Technical Interview']"),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='min_ug_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='qualifications',
            field=models.JSONField(default=list, help_text="e.g. ['B.Tech', 'M.Tech']"),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. 4.5 - 7.5 LPA', max_length=255),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Hyderabad, Remote', max_length=255),
        ),
    ]
