# Generated by Django 5.1.15 on 2026-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_placementdrive_chat_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='excluded_rolls',
            field=models.JSONField(blank=True, default=list, help_text='List of roll numbers explicitly excluded from this drive'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='manual_students',
            field=models.JSONField(blank=True, default=list, help_text='List of roll numbers explicitly added to this drive'),
        ),
    ]
