# Generated by Django 5.1.15 on 2026-03-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_placementdrive_excluded_rolls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='neural_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic AI components (skills, blurbs, roles)'),
        ),
    ]
