# Generated by Django 5.1.15 on 2026-03-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_placementdrive_neural_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='included_rolls',
            field=models.JSONField(blank=True, default=list, help_text='Roll numbers specifically targetted if is_inclusion_mode is active'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='is_inclusion_mode',
            field=models.BooleanField(default=False, help_text='If true, only students in included_rolls (plus manual_students) are eligible'),
        ),
    ]
