# Generated by Django 5.1.15 on 2026-03-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_placementdrive_included_rolls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='auto_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='reminder_config',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'3_days': true, '1_day': true}"),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='tpo_notes',
            field=models.TextField(blank=True, help_text='Strategy notes for TPOs'),
        ),
    ]
