# Generated by Django 5.0.3 on 2026-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auip_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Set to False once assigned to a real institution'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Set to True once migrations are finished'),
        ),
    ]
