# Generated by Django 5.0.3 on 2026-02-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auip_tenant', '0002_client_is_available_client_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_ready',
        ),
    ]
