# Generated by Django 5.1.15 on 2026-03-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_ai_evaluation_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='question',
            new_name='question_mapping',
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('attempt', 'question_mapping')},
        ),
        migrations.AlterUniqueTogether(
            name='examquestionmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='allow_resume',
            field=models.BooleanField(default=True, help_text='Allow students to resume if disconnected'),
        ),
        migrations.AddField(
            model_name='exam',
            name='device_restriction',
            field=models.CharField(choices=[('ANY', 'Any Device'), ('LAPTOP_ONLY', 'Laptop/Desktop Only')], default='LAPTOP_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='enable_microphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='enable_webcam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_results_immediately',
            field=models.BooleanField(default=False, help_text='If false, results withheld until end_time'),
        ),
        migrations.AddField(
            model_name='exam',
            name='strict_mode',
            field=models.BooleanField(default=False, help_text='Auto-terminate exam on reaching violation threshold'),
        ),
        migrations.AddField(
            model_name='exam',
            name='violation_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='compilation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Output from sandbox executor'),
        ),
        migrations.AddField(
            model_name='examanticheatlog',
            name='evidence_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='coding_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Test cases, boilerplate code, memory/time limits'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Can hold code or descriptive text', null=True),
        ),
        migrations.AlterField(
            model_name='examanticheatlog',
            name='event_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Lost Focus'), ('FULLSCREEN_EXIT', 'Fullscreen Exit'), ('DEV_TOOLS_DETECTED', 'Developer Tools Detected'), ('SNAPSHOT_AI_VIOLATION', 'AI Snapshot Violation'), ('DEVICE_CHANGE', 'Attempted Device Change')], max_length=30),
        ),
        migrations.AlterField(
            model_name='examquestionmapping',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MULTI_SELECT', 'Multiple Select'), ('SHORT_ANSWER', 'Short Answer'), ('CODING', 'Coding/Lab'), ('APTITUDE', 'Aptitude/Logical')], default='MCQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='text',
            field=models.TextField(help_text='Detailed problem description or scenario'),
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='examquestionmapping',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examsection'),
        ),
    ]
