# Generated by Django 5.1.15 on 2026-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_question_examanswer_question_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanticheatlog',
            name='faculty_feedback',
            field=models.TextField(blank=True, help_text='Reasoning for verification/falsification', null=True),
        ),
        migrations.AddField(
            model_name='examanticheatlog',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set by faculty to confirm violation'),
        ),
    ]
