# Generated by Django 5.0.3 on 2026-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('ESC_PRESS', 'ESC Press'), ('FOCUS_LOST', 'Focus Lost'), ('OTHER', 'Other')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AntiCheat Log',
                'verbose_name_plural': 'AntiCheat Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
