# Generated by Django 5.1.15 on 2026-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Enterprise-Grade Academic Cloud', max_length=120)),
                ('hero_heading', models.TextField(default='The Operating System for Higher Education')),
                ('hero_subtext', models.TextField(default='AUIP connects students, faculty, and administration through an AI-powered, unified digital infrastructure. Experience zero-trust security and intelligent academic governance.')),
                ('hero_cta_primary', models.CharField(default='Access Portals', max_length=80)),
                ('hero_cta_secondary', models.CharField(default='Read Whitepaper', max_length=80)),
                ('portal_student_title', models.CharField(default='Student Portal', max_length=80)),
                ('portal_student_desc', models.TextField(default='Access your academic records, intelligent resume studio, placement opportunities, and personalized AI assistant.')),
                ('portal_institution_title', models.CharField(default='Institutional Gateway', max_length=80)),
                ('portal_institution_desc', models.TextField(default='Unified access for University Administrators and Faculty. Manage cohorts, analytics, and departmental governance.')),
                ('about_badge', models.CharField(default='Next-Generation Infrastructure', max_length=120)),
                ('about_heading', models.TextField(default='Built for scale, designed for performance.')),
                ('about_body', models.TextField(default='The Adaptive University Intelligence Platform (AUIP) replaces fragmented legacy systems with a singular, high-performance ecosystem. Powered by advanced Machine Learning analytics and robust Tenant Schema isolation, we ensure uncompromised data integrity.')),
                ('about_bullets', models.TextField(default='Multi-tenant architecture ensuring isolated data lakes.\nAI-driven talent discovery and placement matching.\nAutomated verifiable credentials and dynamic portfolios.\nReal-time institutional health monitoring dashboards.', help_text='One bullet per line.')),
                ('whitepaper_heading', models.CharField(default='The AUIP Whitepaper', max_length=120)),
                ('whitepaper_subtext', models.TextField(default='Dive deep into our technical architecture, AI implementation frameworks, and the economic model of next-generation higher education systems.')),
                ('whitepaper_pdf_url', models.URLField(blank=True, default='', help_text='Public URL to the PDF file.')),
                ('whitepaper_view_url', models.URLField(blank=True, default='', help_text='Embeddable / viewable URL (e.g. Google Drive embed).')),
                ('footer_tagline', models.CharField(default='Advancing global education through intelligent computing algorithms and robust infrastructure.', max_length=200)),
                ('contact_email', models.EmailField(default='contact@auip.edu', max_length=254)),
                ('copyright_text', models.CharField(default='© 2026 AUIP Foundation. All Systems Operational.', max_length=200)),
                ('nav_links', models.TextField(default='About,#about\nPlatform,#features\nWhitepaper,#whitepaper\nContact,#contact', help_text='One link per line as: Label,href')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
            },
        ),
    ]
