# Generated by Django 5.1.15 on 2026-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='banner_enabled',
            field=models.BooleanField(default=False, help_text='Show a top-of-page announcement banner.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='banner_link',
            field=models.URLField(blank=True, default='', help_text='Optional URL the banner links to.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='banner_text',
            field=models.CharField(blank=True, default='', help_text="Short message, e.g. 'Launching Sprint 3 — Placement Module now live!'", max_length=200),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='banner_type',
            field=models.CharField(choices=[('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='faq_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='faq_items',
            field=models.TextField(blank=True, default='', help_text="One FAQ per block separated by '---'. Format:\nQ: <question>\nA: <answer>"),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_1_desc',
            field=models.TextField(default='Placement readiness scoring, at-risk detection, and auto-personalized mock assignments.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_1_title',
            field=models.CharField(default='AI Governance Brain', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_2_desc',
            field=models.TextField(default='Quad-Segment Cookie Fragmentation, HMAC key rotation, and device fingerprinting.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_2_title',
            field=models.CharField(default='Quantum Shield Auth', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_3_desc',
            field=models.TextField(default='Every institution gets its own PostgreSQL schema. Cross-tenant queries are structurally impossible.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_3_title',
            field=models.CharField(default='Multi-Tenant Isolation', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_4_desc',
            field=models.TextField(default='AND/OR/nested logic for placement drives. One-student-one-job enforcement built-in.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_4_title',
            field=models.CharField(default='Dynamic Eligibility Engine', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_5_desc',
            field=models.TextField(default='WebSocket-driven dashboards for TPOs with placement stats, department-wise breakdowns.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_5_title',
            field=models.CharField(default='Real-Time Analytics', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_6_desc',
            field=models.TextField(default='AI-powered resume builder with verifiable credentials and ATS scoring.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_6_title',
            field=models.CharField(default='Smart Resume Studio', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='seo_description',
            field=models.TextField(default='AUIP Platform connects students, faculty, and administration through AI-powered, zero-trust digital infrastructure.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='seo_og_image',
            field=models.URLField(blank=True, default='', help_text='Open Graph image URL (1200×630px recommended).'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='seo_title',
            field=models.CharField(default='AUIP – The Operating System for Higher Education', max_length=120),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='social_github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='social_linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='social_twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='social_youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='stat_active_users',
            field=models.CharField(default='4.2k', help_text="e.g. '4.2k', '12,000'", max_length=20),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='stat_ai_queries',
            field=models.CharField(default='1.2M', help_text="e.g. '1.2M'", max_length=20),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='stat_institutions',
            field=models.CharField(default='34+', help_text="e.g. '34+'", max_length=20),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='stat_placement_rate',
            field=models.CharField(default='98%', help_text="e.g. '98%'", max_length=20),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='stats_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='testimonials',
            field=models.TextField(blank=True, default='', help_text="One testimonial per block separated by '---'. Each block:\nName: <name>\nRole: <role / institution>\nQuote: <quote text>"),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='testimonials_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
