# Generated by Django 5.1.15 on 2026-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_landingcontent_banner_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. Lead Architect & Founder', max_length=120)),
                ('bio', models.TextField(blank=True, default='', help_text='Short 1–2 sentence bio.')),
                ('photo_url', models.URLField(blank=True, default='', help_text='Direct URL to a photo (square recommended, min 200×200px). Leave blank to show initials avatar.')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first.')),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='about_image',
            field=models.URLField(blank=True, default='', help_text='Optional image shown beside the About text (replaces the mock dashboard card).'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='favicon_url',
            field=models.URLField(blank=True, default='', help_text='URL to 32×32 favicon (ICO or PNG).'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_1_icon',
            field=models.CharField(default='Brain', help_text='Lucide icon name (e.g. Brain, ShieldCheck, Users)', max_length=40),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_2_icon',
            field=models.CharField(default='ShieldCheck', max_length=40),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_3_icon',
            field=models.CharField(default='Users', max_length=40),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_4_icon',
            field=models.CharField(default='BookOpen', max_length=40),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_5_icon',
            field=models.CharField(default='BarChart3', max_length=40),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='feature_6_icon',
            field=models.CharField(default='FileText', max_length=40),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='hero_bg_image',
            field=models.URLField(blank=True, default='', help_text='Optional full-width hero background image URL. Leave blank for gradient glow.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='logo_alt',
            field=models.CharField(default='AUIP Platform', help_text='Alt text for logo image.', max_length=80),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='Full URL to your logo image (PNG/SVG, recommended transparent background). Leave blank to show text logo.'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='social_instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='team_section_enabled',
            field=models.BooleanField(default=False, help_text="Show the 'Our Team' section on the landing page."),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='team_section_heading',
            field=models.CharField(default='Built by a passionate team', max_length=120),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='team_section_subtext',
            field=models.CharField(default='Meet the people behind the platform.', max_length=300),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='whitepaper_cover_image',
            field=models.URLField(blank=True, default='', help_text='Optional thumbnail shown when no view_url is set.'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='banner_enabled',
            field=models.BooleanField(default=False, help_text='Show top-of-page announcement strip.'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='banner_link',
            field=models.URLField(blank=True, default='', help_text='Optional URL the banner text links to.'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='banner_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='banner_type',
            field=models.CharField(choices=[('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Amber)')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='faq_items',
            field=models.TextField(blank=True, default='', help_text='Separate entries with ---\nFormat:\nQ: <question>\nA: <answer>'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='nav_links',
            field=models.TextField(default='About,#about\nPlatform,#features\nTeam,#team\nWhitepaper,#whitepaper\nContact,#contact', help_text='One link per line: Label,href'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='seo_og_image',
            field=models.URLField(blank=True, default='', help_text='Open Graph image (1200×630px recommended).'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='stat_active_users',
            field=models.CharField(default='4.2k', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='stat_ai_queries',
            field=models.CharField(default='1.2M', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='stat_institutions',
            field=models.CharField(default='34+', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='stat_placement_rate',
            field=models.CharField(default='98%', max_length=20),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='testimonials',
            field=models.TextField(blank=True, default='', help_text='Separate entries with ---\nFormat:\nName: <name>\nRole: <role / institution>\nQuote: <quote text>'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='whitepaper_pdf_url',
            field=models.URLField(blank=True, default='', help_text='Direct URL to the PDF file (used for Download button).'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='whitepaper_view_url',
            field=models.URLField(blank=True, default='/whitepaper.html', help_text='URL for the iframe viewer (set to /whitepaper.html to use the built-in page).'),
        ),
    ]
