# Generated by Django 5.0.3 on 2026-02-10 04:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=10, verbose_name='User Role')),
                ('avatar_filename', models.CharField(default='default_avatar_1.png', max_length=255, verbose_name='Local avatar filename')),
                ('avatar_url', models.CharField(blank=True, max_length=512, validators=[django.core.validators.URLValidator()], verbose_name='Remote avatar URL')),
                ('need_password_reset', models.BooleanField(default=False)),
                ('first_time_login', models.BooleanField(default=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128)),
                ('jti', models.CharField(blank=True, max_length=255, null=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoreStudent',
            fields=[
                ('stu_ref', models.CharField(help_text='Unique student reference (e.g., 2021-CS-001)', max_length=20, primary_key=True, serialize=False, verbose_name='Student Reference')),
                ('roll_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Roll Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('OTHER', 'Other')], max_length=100, verbose_name='Department')),
                ('batch_year', models.IntegerField(help_text='Year of admission', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Batch Year')),
                ('current_semester', models.IntegerField(help_text='Current semester (1-8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Current Semester')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Current CGPA (0.00 - 10.00)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='CGPA')),
                ('tenth_percentage', models.DecimalField(decimal_places=2, help_text='10th grade percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='10th %')),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, help_text='12th grade percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='12th %')),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Overall attendance percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Attendance %')),
                ('official_email', models.EmailField(db_index=True, help_text='Official institutional email', max_length=254, unique=True, verbose_name='Official Email')),
                ('status', models.CharField(choices=[('SEEDED', 'Seeded'), ('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='SEEDED', max_length=20, verbose_name='Status')),
                ('seeded_at', models.DateTimeField(auto_now_add=True, verbose_name='Seeded At')),
                ('seeded_by', models.CharField(help_text='Admin/SPOC who added this student', max_length=255, verbose_name='Seeded By')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_eligible_for_placement', models.BooleanField(default=False, help_text='Eligible for placement drives', verbose_name='Placement Eligible')),
                ('placement_eligibility_reason', models.TextField(blank=True, help_text='Reason if not eligible', verbose_name='Eligibility Reason')),
            ],
            options={
                'verbose_name': 'Core Student',
                'verbose_name_plural': 'Core Students',
                'db_table': 'core_students',
                'ordering': ['stu_ref'],
                'indexes': [models.Index(fields=['status'], name='idx_core_student_status'), models.Index(fields=['batch_year'], name='idx_core_student_batch'), models.Index(fields=['department'], name='idx_core_student_dept'), models.Index(fields=['is_eligible_for_placement'], name='idx_core_student_eligible')],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('refresh_jti', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('device_salt', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('browser_info', models.CharField(blank=True, max_length=128)),
                ('login_method', models.CharField(default='web', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_seen_location', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_user_agent', models.CharField(blank=True, max_length=512)),
                ('requested_device', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RememberedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=128, unique=True)),
                ('trusted', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device', models.CharField(blank=True, default='web', max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remembered Device',
                'verbose_name_plural': 'Remembered Devices',
            },
        ),
        migrations.CreateModel(
            name='StudentInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Secure activation token', max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_used', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(help_text='The core student record this invitation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='identity.corestudent')),
            ],
            options={
                'verbose_name': 'Student Invitation',
                'verbose_name_plural': 'Student Invitations',
                'db_table': 'student_invitations',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('admission_year', models.CharField(blank=True, max_length=10)),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('enrolled_subjects', models.ManyToManyField(blank=True, related_name='students', to='identity.subject')),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='identity.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='identity_us_email_bcdd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='identity_us_role_d94918_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['token_hash'], name='identity_bl_token_h_a159d7_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['user', 'expires_at'], name='identity_bl_user_id_5a1340_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['jti'], name='identity_bl_jti_ce33e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blacklistedaccesstoken',
            unique_together={('user', 'token_hash')},
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'is_active'], name='identity_lo_user_id_2ca654_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'refresh_jti', 'is_active'], name='identity_lo_user_id_c36064_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['expires_at'], name='identity_lo_expires_09da73_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['device_fingerprint'], name='identity_lo_device__f6beb5_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['refresh_token_hash'], name='identity_lo_refresh_50c058_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['device_salt'], name='identity_lo_device__fa740a_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', 'created_at'], name='identity_pa_user_id_632ebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='passwordhistory',
            unique_together={('user', 'password_hash')},
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['token_hash'], name='identity_pa_token_h_152d72_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user', 'created_at'], name='identity_pa_user_id_35370e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['roll_number'], name='identity_st_roll_nu_7ef4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['batch'], name='identity_st_batch_647128_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['department'], name='identity_te_departm_c2d32e_idx'),
        ),
    ]
