# Generated by Django 5.2.5 on 2026-02-10 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_institution_alter_user_role_corestudent_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stu_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='identity.corestudent', verbose_name='Core Student Reference'),
        ),
    ]
