# Generated by Django 5.2.5 on 2026-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_stu_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='registration_data',
            field=models.JSONField(blank=True, help_text='Detailed registration application data', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='schema_name',
            field=models.CharField(blank=True, help_text='Database schema name for this institution', max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEW', 'Under Review'), ('MORE_INFO', 'More Info Requested')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='student_count_estimate',
            field=models.IntegerField(default=0),
        ),
    ]
