# Generated by Django 5.2.5 on 2026-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_institution_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='corestudent',
            name='idx_core_student_batch',
        ),
        migrations.RemoveIndex(
            model_name='corestudent',
            name='idx_core_student_dept',
        ),
        migrations.RemoveIndex(
            model_name='corestudent',
            name='idx_core_student_eligible',
        ),
        migrations.RenameIndex(
            model_name='corestudent',
            new_name='core_studen_status_0cc21d_idx',
            old_name='idx_core_student_status',
        ),
        migrations.AddField(
            model_name='corestudent',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='current_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='is_eligible_for_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='official_email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='placement_eligibility_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='roll_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='seeded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='seeded_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='status',
            field=models.CharField(choices=[('SEEDED', 'Seeded'), ('INVITED', 'Invited'), ('VERIFIED', 'Verified'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='SEEDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='stu_ref',
            field=models.CharField(help_text='Unique student reference (e.g., 2021-CS-001)', max_length=50, primary_key=True, serialize=False, verbose_name='Student Reference'),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='corestudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='corestudent',
            index=models.Index(fields=['roll_number'], name='core_studen_roll_nu_0ad86b_idx'),
        ),
        migrations.AddIndex(
            model_name='corestudent',
            index=models.Index(fields=['institution'], name='core_studen_institu_61693e_idx'),
        ),
    ]
