# Generated by Gemini — Manual Migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_remove_corestudent_idx_core_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='last_secure_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
