# Generated by Gemini — Manual Migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_loginsession_last_secure_check'),
    ]

    operations = [
        # Remove the global uniqueness constraint
        migrations.AlterField(
            model_name='remembereddevice',
            name='device_hash',
            field=models.CharField(max_length=128),
        ),
        # Add the composite uniqueness constraint
        migrations.AlterUniqueTogether(
            name='remembereddevice',
            unique_together={('user', 'device_hash')},
        ),
    ]
