# Generated by Django 5.2.5 on 2025-09-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentprofile_teacherprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='passwordhistory',
            unique_together={('user', 'password_hash')},
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['token'], name='users_passw_token_91e9e5_idx'),
        ),
    ]
