# Generated by Django 5.0.3 on 2026-02-18 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_fix_remembered_device_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='tenant_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
