# Generated by Django 5.2.5 on 2025-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_blacklistedaccesstoken_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistedaccesstoken',
            name='token',
        ),
        migrations.AddField(
            model_name='blacklistedaccesstoken',
            name='token_hash',
            field=models.CharField(default='dummy hash', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
