# Generated by Django 5.0.3 on 2026-02-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_loginsession_tenant_email_loginsession_tenant_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remembereddevice',
            name='trust_cookie_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
