# Generated by Django 5.2.5 on 2025-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_blacklistedaccesstoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
