# Generated by Django 5.0.3 on 2026-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_add_trust_cookie_hash_to_remembered_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='remembereddevice',
            name='trusted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
