# Generated by Django 5.2.5 on 2025-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_blacklistedaccesstoken_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
