# Generated by Django 5.0.3 on 2026-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_add_trusted_until_to_remembered_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
