# Generated by Django 5.0.3 on 2026-02-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_loginsession_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='previous_jti',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
