# Generated by Django 5.2.5 on 2025-09-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_blacklistedaccesstoken_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='token_hash',
            field=models.CharField(default='makemigrate_for_users', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
