# Generated by Django 5.1.15 on 2026-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_loginsession_previous_jti_loginsession_rotated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('institution_name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hod_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Institution Interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
