# Generated by Django 5.2.5 on 2025-09-25 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_blacklistedaccesstoken_token_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('refresh_jti', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='blacklistedaccesstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blacklistedaccesstoken',
            name='jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='requested_device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='requested_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='requested_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_filename',
            field=models.CharField(default='default_avatar_1.png', max_length=255, verbose_name='Local avatar filename'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=512, validators=[django.core.validators.URLValidator()], verbose_name='Remote avatar URL'),
        ),
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='token_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='blacklistedaccesstoken',
            unique_together={('user', 'token_hash')},
        ),
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['token_hash'], name='users_black_token_h_74fcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['user', 'expires_at'], name='users_black_user_id_893eac_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', 'created_at'], name='users_passw_user_id_053982_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user', 'created_at'], name='users_passw_user_id_adc1b0_idx'),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'is_active'], name='users_login_user_id_1dc2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['expires_at'], name='users_login_expires_a64231_idx'),
        ),
    ]
