# Generated by Django 5.0.3 on 2026-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_institutioninterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinvitation',
            name='token',
            field=models.CharField(db_index=True, help_text='Secure activation token', max_length=512, unique=True),
        ),
    ]
