# Generated by Django 5.2.5 on 2025-09-25 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_loginsession_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=128, unique=True)),
                ('trusted', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remembered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remembered Device',
                'verbose_name_plural': 'Remembered Devices',
            },
        ),
    ]
