# Generated by Django 5.0.3 on 2026-02-20 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_fix_token_length_and_contact_email_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='remembereddevice',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='remembereddevice',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='remembereddevice',
            name='tenant_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remembereddevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remembered_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
