# Generated by Django 5.2.5 on 2025-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remembereddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ailed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Failed login attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account lockout until'),
        ),
    ]
