# Generated by Django 5.0.3 on 2026-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_remembereddevice_tenant_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remembereddevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='remembereddevice',
            name='role',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='remembereddevice',
            unique_together={('user', 'device_hash', 'tenant_user_id', 'tenant_schema', 'role')},
        ),
    ]
