# Generated by Django 5.2.5 on 2025-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_ailed_login_attempts_user_lockout_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ailed_login_attempts',
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
