# Generated by Django 5.2.5 on 2025-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_ailed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='token_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='token_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
