# Generated by Django 5.1.15 on 2026-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_alter_remembereddevice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='certificate_id',
            field=models.UUIDField(blank=True, default=None, help_text='Verifiable certificate identifier', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='URL to the generated PDF certificate', max_length=500, null=True),
        ),
    ]
