# Generated by Django 5.0.3 on 2026-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_institution_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='certificate_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='certificate_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256 fingerprint of the X.509 certificate', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='certificate_serial',
            field=models.CharField(blank=True, help_text='X.509 serial number (hex)', max_length=128, null=True),
        ),
    ]
