# Generated by Django 5.2.5 on 2025-09-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_blacklistedaccesstoken_token_hash_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetrequest',
            name='users_passw_token_91e9e5_idx',
        ),
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='token',
            new_name='token_hash',
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['token_hash'], name='users_passw_token_h_027995_idx'),
        ),
    ]
