# Generated by Django 5.1.15 on 2026-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0018_institution_certificate_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='activation_cert_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='activation_cert_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256 fingerprint of the activation certificate', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='activation_cert_id',
            field=models.UUIDField(blank=True, default=None, help_text='Sovereign activation certificate identifier', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='activation_cert_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='activation_cert_serial',
            field=models.CharField(blank=True, help_text='Activation cert X.509 serial number (hex)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='activation_cert_url',
            field=models.URLField(blank=True, help_text='URL to the sovereign activation certificate PDF', max_length=500, null=True),
        ),
    ]
