# Generated by Django 5.2.5 on 2025-10-03 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_passwordresetrequest_users_passw_token_91e9e5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remembereddevice',
            name='last_used',
        ),
        migrations.AddField(
            model_name='loginsession',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remembereddevice',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
