# Generated by Django 5.2.5 on 2025-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_remembereddevice_last_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='loginsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loginsession',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['device_fingerprint'], name='users_login_device__50c2b8_idx'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.subject'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.subject'),
        ),
    ]
