# Generated by Django 5.1.15 on 2026-03-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0019_add_activation_cert_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('PROVISIONING', 'Provisioning in Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEW', 'Under Review'), ('MORE_INFO', 'More Info Requested'), ('ABORTED', 'Provisioning Aborted')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SchemaUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63)),
                ('version_label', models.CharField(help_text='Auto-generated version label, e.g. v1, v2', max_length=50)),
                ('migrations_applied', models.JSONField(default=list, help_text='List of migration names that were applied')),
                ('migrations_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial (Some migrations failed)')], default='IN_PROGRESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_updates', to='identity.institution')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_updates_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schema Update History',
                'verbose_name_plural': 'Schema Update Histories',
                'ordering': ['-started_at'],
            },
        ),
    ]
