# Generated by Django 5.2.5 on 2025-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_subject_alter_loginsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='refresh_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['refresh_token_hash'], name='users_login_refresh_673a6d_idx'),
        ),
    ]
