# Generated by Django 5.2.5 on 2025-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_loginsession_refresh_token_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='device_salt',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['device_salt'], name='users_login_device__42ee19_idx'),
        ),
    ]
