# Generated by Django 5.2.5 on 2025-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_loginsession_device_salt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='browser_info',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='device_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='last_seen_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='login_method',
            field=models.CharField(default='web', max_length=32),
        ),
    ]
