# Generated by Django 5.2.5 on 2025-10-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_loginsession_browser_info_loginsession_device_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['jti'], name='users_black_jti_bf5648_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'refresh_jti', 'is_active'], name='users_login_user_id_4b03a5_idx'),
        ),
    ]
