# Generated by Django 5.0.3 on 2026-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_blacklistedaccesstoken_users_black_jti_bf5648_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remembereddevice',
            name='device',
            field=models.CharField(blank=True, default='web', max_length=50),
        ),
        migrations.AddField(
            model_name='remembereddevice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='remembereddevice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='remembereddevice',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
