# Generated by Django 5.0.3 on 2026-02-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remembereddevice_device_remembereddevice_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
